== Links

この章では、外部Webページへのリンクを本文に直接記載する方法と、
文書属性を使ってURLを一元管理する方法を説明します。

=== Direct Links

URLの後ろに角括弧を付けると、外部Webページへのリンクを作成できます。
角括弧の中には、リンクとして表示する文字列を指定します。

[source,asciidoc]
....
https://docs.asciidoctor.org/[Asciidoctor Documentation]
....

表示結果は次のとおりです。

https://docs.asciidoctor.org/[Asciidoctor Documentation]

リンクは、次のように本文中へ直接埋め込むこともできます。

[source,asciidoc]
....
詳細は https://docs.asciidoctor.org/[Asciidoctor Documentation] を参照してください。
....

表示結果は次のとおりです。

詳細は https://docs.asciidoctor.org/[Asciidoctor Documentation] を参照してください。

URL自体をリンクの表示文字列にする場合は、角括弧を空にします。

[source,asciidoc]
....
https://docs.asciidoctor.org/[]
....

表示結果は次のとおりです。

https://docs.asciidoctor.org/[]

=== Managing URLs with Attributes

複数の場所で使用するURLは、本文の `.adoc` ファイルへ直接記載せず、
文書属性として `link-attributes.adoc` にまとめて定義できます。
この方法では、リンク先を1か所で管理できます。

`index.adoc` の文書ヘッダーで、URLを定義したファイルを読み込みます。

[source,asciidoc]
....
include::link-attributes.adoc[]
....

`link-attributes.adoc` 自体は、次のように記述できます。
属性名は任意ですが、URLであることが分かるように `-url` を付けると管理しやすくなります。
リンク先を追加する場合は、同じ形式で属性を1行ずつ追加します。

.link-attributes.adoc
[source,asciidoc]
....
// Define external URLs as document attributes in this file.
:asciidoctor-docs-url: https://docs.asciidoctor.org/
....

本文では、URLの代わりに `{属性名}` を使用します。

[source,asciidoc]
....
詳細は {asciidoctor-docs-url}[Asciidoctor Documentation] を参照してください。
....

表示結果は次のとおりです。

詳細は {asciidoctor-docs-url}[Asciidoctor Documentation] を参照してください。

PDFでは、表示されたリンクをクリックするとリンク先のWebページを開けます。

=== Links Within This Document

同じ文書内の章、図、表などにリンクするには、リンク先にアンカーIDを指定してから、
`<<アンカーID,表示文字列>>` で参照します。PDFでは、リンクをクリックすると該当する
場所へ移動します。

章題へリンクする場合は、見出しの直前に `[[アンカーID]]` を記載します。
このサンプルの `Title and Cover Page` 章には、次のアンカーを設定しています。

[source,asciidoc]
....
[[title-and-cover-page]]
== Title and Cover Page
....

本文からは、次のようにリンクします。

[source,asciidoc]
....
詳細は <<title-and-cover-page,Title and Cover Page>> を参照してください。
....

表示結果は次のとおりです。

詳細は <<title-and-cover-page,Title and Cover Page>> を参照してください。

図へリンクする場合は、図のキャプションの直後、画像ブロックの直前に
`[#アンカーID]` を記載します。このサンプルでは、Space Cubics logoの図に
次のアンカーを設定しています。

[source,asciidoc]
....
.Space Cubics logo
[#spacecubics-logo-figure]
image::sc-logo-ffffff-414551.svg[Space Cubics logo,pdfwidth=45mm,align=center]
....

リンクテキストには任意の文字列を指定できます。図番号で参照する場合は、
次のように記載します。

[source,asciidoc]
....
詳細は <<spacecubics-logo-figure,Figure 1>> を参照してください。
....

表示結果は次のとおりです。

詳細は <<spacecubics-logo-figure,Figure 1>> を参照してください。

表とコードブロックにも、図と同じようにキャプションの直後、対象ブロックの直前へ
`[#アンカーID]` を記載することでリンクを設定できます。リンクテキストには、
図番号、キャプション名、説明文など、用途に応じた任意の文字列を指定できます。
